//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LivrariaSorocaba.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorBooks
    {
        public int ID { get; set; }
        public int IDAuthor { get; set; }
        public int IDBook { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Books Books { get; set; }
    }
}
